# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '2.1.403'
  publishArtifacts: false

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK $(dotnetSdkVersion)
  inputs:
    version: $(dotnetSdkVersion)

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build SymbioticTS.sln ($(buildConfiguration))

- task: DotNetCoreCLI@2
  displayName: Run tests ($(buildConfiguration))
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    publishTestResults: true
    arguments: '--no-build --no-restore -c $(buildConfiguration)'

- script: dotnet build Example\Example.sln --configuration $(buildConfiguration)
  displayName: Build Example.sln ($(buildConfiguration))

- task: PublishBuildArtifacts@1
  displayName: Publish __output
  condition: or(and(succeededOrFailed(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')), variables.publishArtifacts)
  inputs:
    PathtoPublish: __output
    ArtifactName: __output
    ArtifactType: Container

- task: PublishBuildArtifacts@1
  displayName: Publish __nuget
  condition: or(and(succeededOrFailed(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')), variables.publishArtifacts)
  inputs:
    PathtoPublish: __nuget
    ArtifactName: __nuget
    ArtifactType: Container
