/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

export enum Color {
    Blue = 0,
    Green = 1,
    Red = 2,
}
