/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { IShapeDto } from './IShapeDto';

export interface IBaseShapeDto extends IShapeDto
{
}
