/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { IBaseShapeDto } from './IBaseShapeDto';
import { IShapeDto } from './IShapeDto';

export interface ICircleDto extends IBaseShapeDto, IShapeDto
{
    readonly diameter: number;
}
