/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { Circle } from './Circle';
import { IShape } from './IShape';
import { Rectangle } from './Rectangle';
import { ViewModelBase } from './ViewModelBase';

export class ShapeViewModel extends ViewModelBase
{
    public shapes?: IShape[];
    public readonly totalShapes: number;
    public readonly rectangles: Rectangle[];
    public readonly totalRectangles?: number;
    public readonly circles: Circle[];
    public readonly totalCircles: number;

    constructor(
        circles: Circle[],
        dateCreated: Date,
        rectangles: Rectangle[],
        totalCircles: number,
        totalShapes: number,
        dateUpdated?: Date,
        shapes?: IShape[],
        totalRectangles?: number)
    {
        super(dateCreated, dateUpdated);

        this.circles = circles;
        this.rectangles = rectangles;
        this.totalCircles = totalCircles;
        this.totalShapes = totalShapes;
        this.shapes = shapes;
        this.totalRectangles = totalRectangles;
    }
}
