/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { Color } from './Color';
import { ShapeBorder } from './ShapeBorder';

export class Triangle
{
    public border: ShapeBorder;
    public color: Color;
    public readonly sides: number;

    constructor(border: ShapeBorder, color: Color, sides: number)
    {
        this.border = border;
        this.color = color;
        this.sides = sides;
    }
}
