/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

export abstract class ViewModelBase {
    public dateCreated: Date;
    public dateUpdated?: Date;

    constructor(dateCreated: Date, dateUpdated?: Date) {
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
    }
}
