/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

import { IRequireTransformDto } from './IRequireTransformDto';

export interface IDtoWithTransformInterfacePropertyDto {
    property: IRequireTransformDto;
}
