/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

import { IDtoWithDateTimeTestClassDto } from './IDtoWithDateTimeTestClassDto';

export class DtoWithDateTimeTestClass {
    public count: number;
    public birthdate: Date;

    constructor(birthdate: Date, count: number) {
        this.birthdate = birthdate;
        this.count = count;
    }

    public static fromDto(dto: IDtoWithDateTimeTestClassDto): DtoWithDateTimeTestClass {
        const birthdate = new Date(dto.birthdate);

        return new DtoWithDateTimeTestClass(birthdate, dto.count);
    }
}
