/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { IDtoSimpleTestClassDto } from './IDtoSimpleTestClassDto';

export class DtoSimpleTestClass
{
    public count: number;
    public name?: string;

    constructor(count: number, name?: string)
    {
        this.count = count;
        this.name = name;
    }

    public static fromDto(dto: IDtoSimpleTestClassDto): DtoSimpleTestClass
    {
        return new DtoSimpleTestClass(dto.count, dto.name);
    }
}
