/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

export interface IDtoWithDateTimeCollectionTestClassDto
{
    count: number;
    birthdate: string[];
}
