/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

export class AnnotatedClass
{
    public property: boolean;

    constructor(property: boolean)
    {
        this.property = property;
    }
}
