/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

// tslint:disable:max-line-length

export class AnnotatedClass {
    public property: boolean;

    constructor(property: boolean) {
        this.property = property;
    }
}
