/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { UnannotatedClass } from './UnannotatedClass';

export class ClassWithUnannotatedNestedProperties
{
    public classProperty?: UnannotatedClass;

    constructor(classProperty?: UnannotatedClass)
    {
        this.classProperty = classProperty;
    }
}
