/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { IUnannotatedInterface } from './IUnannotatedInterface';
import { UnannotatedClass } from './UnannotatedClass';
import { UnannotatedEnum } from './UnannotatedEnum';

export class ClassWithUnannotatedProperties
{
    public classProperty?: UnannotatedClass;
    public enumProperty: UnannotatedEnum;
    public interfaceProperty: IUnannotatedInterface;

    constructor(enumProperty: UnannotatedEnum, interfaceProperty: IUnannotatedInterface, classProperty?: UnannotatedClass)
    {
        this.enumProperty = enumProperty;
        this.interfaceProperty = interfaceProperty;
        this.classProperty = classProperty;
    }
}
