/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

import { ClassWithUnannotatedInterfaceInterface } from './ClassWithUnannotatedInterfaceInterface';

export class ClassWithUnannotatedInterface implements ClassWithUnannotatedInterfaceInterface {
}
