/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { UnnanotatedArrayClass } from './UnnanotatedArrayClass';

export class ClassWithUnannotatedArrayClassProperty
{
    public arrayClassProperty?: UnnanotatedArrayClass[];

    constructor(arrayClassProperty?: UnnanotatedArrayClass[])
    {
        this.arrayClassProperty = arrayClassProperty;
    }
}
