/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

// tslint:disable:max-line-length

import { IUnannotatedInterface } from './IUnannotatedInterface';
import { UnannotatedClass } from './UnannotatedClass';
import { UnannotatedEnum } from './UnannotatedEnum';

// tslint:disable-next-line:interface-name
export interface ClassWithUnannotatedInterfacePropertiesInterface {
    readonly classProperty?: UnannotatedClass;
    readonly enumProperty: UnannotatedEnum;
    readonly interfaceProperty: IUnannotatedInterface;
}
