/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

// tslint:disable:max-line-length

import { UnnanotatedArrayClass } from './UnnanotatedArrayClass';

export class ClassWithUnannotatedArrayClassProperty {
    public arrayClassProperty?: UnnanotatedArrayClass[];

    constructor(arrayClassProperty?: UnnanotatedArrayClass[]) {
        this.arrayClassProperty = arrayClassProperty;
    }
}
