/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

// tslint:disable-next-line:interface-name no-empty-interface
export interface ClassWithUnannotatedInterfaceInterface {
}
