/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { ClassWithUnannotatedInterfacePropertiesInterface } from './ClassWithUnannotatedInterfacePropertiesInterface';
import { IUnannotatedInterface } from './IUnannotatedInterface';
import { UnannotatedClass } from './UnannotatedClass';
import { UnannotatedEnum } from './UnannotatedEnum';

export class ClassWithUnannotatedInterfaceProperties implements ClassWithUnannotatedInterfacePropertiesInterface
{
    public readonly classProperty?: UnannotatedClass;
    public readonly enumProperty: UnannotatedEnum;
    public readonly interfaceProperty: IUnannotatedInterface;

    constructor(enumProperty: UnannotatedEnum, interfaceProperty: IUnannotatedInterface, classProperty?: UnannotatedClass)
    {
        this.enumProperty = enumProperty;
        this.interfaceProperty = interfaceProperty;
        this.classProperty = classProperty;
    }
}
