/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { ClassWithUnannotatedBaseBase } from './ClassWithUnannotatedBaseBase';

export class ClassWithUnannotatedBase extends ClassWithUnannotatedBaseBase
{
    constructor()
    {
        super();
    }
}
