/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

/* tslint:disable:max-line-length */

export class ClassWithNetFrameworkProperties {
    public dateTimeProperty: Date;
    public enumerableIntProperty: number[];
    public intArrayProperty?: number[];
    public intProperty: number;
    public nullableIntProperty?: number;
    public stringProperty?: string;

    constructor(
        dateTimeProperty: Date,
        enumerableIntProperty: number[],
        intProperty: number,
        intArrayProperty?: number[],
        nullableIntProperty?: number,
        stringProperty?: string) {
        this.dateTimeProperty = dateTimeProperty;
        this.enumerableIntProperty = enumerableIntProperty;
        this.intProperty = intProperty;
        this.intArrayProperty = intArrayProperty;
        this.nullableIntProperty = nullableIntProperty;
        this.stringProperty = stringProperty;
    }
}
