/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

// tslint:disable:max-line-length

import { InterfaceWithUnannotatedInterfaceInterface } from './InterfaceWithUnannotatedInterfaceInterface';

// tslint:disable-next-line:no-empty-interface
export interface InterfaceWithUnannotatedInterface extends InterfaceWithUnannotatedInterfaceInterface {
}
