/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { InterfaceWithUnannotatedInterfaceInterface } from './InterfaceWithUnannotatedInterfaceInterface';

export interface InterfaceWithUnannotatedInterface extends InterfaceWithUnannotatedInterfaceInterface
{
}
