/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

export interface IDtoWithOptionalPropertyTestClassDto
{
    readonly count?: number;
    name?: string;
}
