/**
 * This file was generated by SymbioticTS.
 * All changes will be lost the next time the file is generated.
 */

import { IClassRequiresTransformDto } from './IClassRequiresTransformDto';

export interface IDtoWithTransformClassPropertyDto
{
    transform?: IClassRequiresTransformDto;
}
